<?php

namespace Tests\Feature;

use App\Models\Replies;
use App\Models\Threads;
use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ParticipateInForumTest extends TestCase
{
    use DatabaseMigrations;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->thread = Threads::factory()->create();
    }

    /**
     * @test
     */
//    public function unauthenticated_users_may_not_add_replies(){
//        $this->expectExcerption('Illuminate\Auth\AuthenticationExcerption');
//        $reply = Replies::factory()->create();
//
//        //dd($this->thread->path().'/replies',$reply->toArray());
////        dd($reply->toArray());
//
//        $this->post($this->thread->path().'/replies',$reply->toArray());
//    }

    /**
     * @test

     */
    public function an_authenticated_user_may_participate_in_forum_threads()
    {

        $this->be($user = User::factory()->make());

//        $thread = Threads::factory()->create();

        $reply = Replies::factory()->create();

        //dd($this->thread->path().'/replies',$reply->toArray());
//        dd($reply->toArray());

        $this->post($this->thread->path().'/replies',$reply->toArray());

        $this->get($this->thread->path())
            ->assertSee($reply->body);
    }


}
