<?php

namespace Tests\Feature;

use App\Models\Replies;
use App\Models\Threads;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ReadThreadsTest extends TestCase
{
    use DatabaseMigrations;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = Threads::factory()->create();
    }

    /**
     * @test
     */
    public function a_user_can_view_all_threads()
    {
//        $thread = Threads::factory()->create();
        $response = $this->get('/threads')
            ->assertSee($this->thread->title);


    }
    /**
     * @test
     */
    function a_user_can_read_a_single_thread(){

//        $thread = Threads::factory()->create();

        $response = $this->get('/threads/'.$this->thread->id)
                     ->assertSee($this->thread->title);
    }

    /**
     * @test
     */
    function a_user_can_read_replies_associated_with_a_thread(){

        $reply = Replies::factory()->create(['threads_id'=>$this->thread->id]);

        $response = $this->get('/threads/'.$this->thread->id)
        ->assertSee($reply->body);

    }
}
